apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-python-autoscaler
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: deployment-notitia-python
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
