apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-python-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: deployment-notitia-python
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
